const { DataTypes } = require("sequelize");
const temps = [
  "Stubborn",
  "Curious",
  "Playful",
  "Adventurous",
  "Active",
  "Fun-loving",
  "Aloof",
  "Clownish",
  "Dignified",
  "Independent",
  "Happy",
  "Wild",
  "Hardworking",
  "Dutiful",
  "Outgoing",
  "Friendly",
  "Alert",
  "Confident",
  "Intelligent",
  "Courageous",
  "Loyal",
  "Brave",
  "Docile",
  "Responsive",
  "Composed",
  "Receptive",
  "Faithful",
  "Loving",
  "Protective",
  "Trainable",
  "Responsible",
  "Energetic",
  "Gentle",
  "Affectionate",
  "Devoted",
  "Assertive",
  "Dominant",
  "Strong Willed",
  "Obedient",
  "Reserved",
  "Kind",
  "Sweet-Tempered",
  "Tenacious",
  "Attentive",
  "Steady",
  "Bold",
  "Proud",
  "Reliable",
  "Fearless",
  "Lively",
  "Self-assured",
  "Cautious",
  "Eager",
  "Good-natured",
  "Spirited",
  "Companionable",
  "Even Tempered",
  "Rugged",
  "Fierce",
  "Refined",
  "Joyful",
  "Agile",
  "Amiable",
  "Excitable",
  "Determined",
  "Self-confidence",
  "Hardy",
  "Calm",
  "Good-tempered",
  "Watchful",
  "Hard-working",
  "Feisty",
  "Cheerful",
  "Sensitive",
  "Easygoing",
  "Adaptable",
  "Trusting",
  "Lovable",
  "Territorial",
  "Keen",
  "Familial",
  "Rational",
  "Bright",
  "Quick",
  "Powerful",
  "Gay",
  "Stable",
  "Quiet",
  "Inquisitive",
  "Strong",
  "Sociable",
  "Patient",
  "Suspicious",
  "Great-hearted",
  "Merry",
  "Vocal",
  "Tolerant",
  "Mischievous",
  "People-Oriented",
  "Bossy",
  "Cunning",
  "Athletic",
  "Boisterous",
  "Cooperative",
  "Trustworthy",
  "Self-important",
  "Respectful",
  "Thoughtful",
  "Generous",
  "Cat-like",
  "Sturdy",
  "Benevolent",
  "Clever",
  "Bubbly",
  "Opinionated",
  "Aggressive",
  "Extroverted",
  "Charming",
  "Unflappable",
  "Spunky",
  "Diligent",
  "Willful",
  "Fast",
  "Vigilant",
];

module.exports = (sequelize) => {
  sequelize.define(
    "dog",
    {
      id: {
        type: DataTypes.UUID,
        primaryKey: true,
        defaultValue: DataTypes.UUIDV4,
      },
      image: {
        type: DataTypes.STRING,
        defaultValue:
          "https://e7.pngegg.com/pngimages/926/944/png-clipart-pluto-mickey-mouse-goofy-dog-pluto-heroes-flower.png",
      },
      name: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      height: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      weight: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      life_span: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      temperament: {
        type: DataTypes.ENUM,
        values: temps,
        allowNull: false,
      },
      created: {
        type: DataTypes.BOOLEAN,
        defaultValue: true,
      },
    },
    { timestamps: false }
  );
};
