const GET_DOGS = "GET_DOGS";
const GET_DOGS_BY_ID = "GET_DOGS_BY_ID";
const CREATE_DOG = "CREATE_DOG";
const ORDER_BY_NAME = "ORDER_BY_NAME";
const ORDER_BY_WEIGHT = "ORDER_BY_WEIGHT";
const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
const GET_DOGS_BY_NAME = "GET_DOGS_BY_NAME";

export {
  GET_DOGS,
  GET_DOGS_BY_ID,
  CREATE_DOG,
  ORDER_BY_NAME,
  ORDER_BY_WEIGHT,
  GET_TEMPERAMENTS,
  GET_DOGS_BY_NAME,
};
